### ISSUE TITLE
Adaptive time stepper fails if number of iterations is 0.

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-autodiff#546]
In that case, the timestep becomes NaN.

**Comment by totto82** [comment]
This is not a problem anymore as the simulator takes at least 1 newton iteration. (minIter is defaulted to 1. )

**Comment by GitPaean** [comment]
I think long time ago, I had the question if we have to do at least one iteration? At that time, the answer I got is we do not have to do that.  So the current understanding is that we better take one Newton iteration even if the initial values are good enough?

**Comment by atgeirr** [comment]
@GitPaean is right: if the current state is good enough to go below the residual thresholds we do not have to take an iteration, this can easily happen if you try to simulate pr verify a steady state, for example at the start of a run.

Therefore while the current minimum iterations default saves us from trouble, it is really just a workaround, the time stepper can still crash if the user specifies 0 minimum (and that should be the default eventually).

Keeping this open until we fix this in the time stepper.

**Comment by andlaus** [comment]
I guess this is not a problem that occurs in practice anymore as the simulator code makes sure that at least one full iteration is done for any substep. closing.

**Comment by atgeirr** [comment]
Don't close this, it should be ok to do no iterations if the changes are small.

**Comment by blattms** [comment]
To close or not to close @atgeirr

**Comment by atgeirr** [comment]
Not! It should be fixed!

**Comment by OPMUSER** [comment]
Can this be closed, as it is nearly 10 months stale?

**Comment by bska** [comment]
> Can this be closed, as it is nearly 10 months stale?

It cannot.  The underlying problem is still present and we need to fix it.
